# Generated by Django 3.2.13 on 2022-11-18 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funding',
            name='now_money',
            field=models.IntegerField(default=0),
        ),
    ]
