# Generated by Django 3.2.13 on 2022-11-18 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='funding',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
